ALTER TABLE "accounts" DROP CONSTRAINT "accounts_card_id_key";--> statement-breakpoint
ALTER TABLE "jars" DROP CONSTRAINT "jars_jar_id_key";--> statement-breakpoint
ALTER TABLE "transactions" DROP CONSTRAINT "transactions_transaction_id_key";--> statement-breakpoint
ALTER TABLE "accounts" DROP COLUMN "card_id";--> statement-breakpoint
ALTER TABLE "jars" DROP COLUMN "jar_id";--> statement-breakpoint
ALTER TABLE "transactions" DROP COLUMN "transaction_id";--> statement-breakpoint
ALTER TABLE "accounts" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "jars" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "id" SET GENERATED BY DEFAULT;